# Generated by Django 2.2.7 on 2019-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0004_auto_20191203_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
