# Generated by Django 2.2.7 on 2019-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_auto_20191203_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product_images')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ready-to-eat', 'Ready to Eat'), ('ready-to-cook', 'Ready to Cook'), ('ready-to-drink', 'Ready to Drink')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
