# Generated by Django 2.2.7 on 2019-12-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0010_auto_20191205_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
