# Generated by Django 2.2.7 on 2019-12-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0011_remove_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
