# Generated by Django 2.2.7 on 2019-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0013_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'COMPLETE')], default=0),
        ),
    ]
