# Generated by Django 2.2.7 on 2019-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0014_auto_20191205_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'DISPATCHED'), (2, 'COMPLETE')], default=0),
        ),
    ]
